import { Router, type IRouter } from "express";
import { ListOffersResponse } from "@workspace/api-zod";

const router: IRouter = Router();

const OFFERS = {
  data: [
    {
      id: "data-1",
      name: "250MB Daily",
      data: "250MB",
      minutes: null,
      sms: null,
      price: 20,
      validity: "24 hours",
      category: "data" as const,
      multipleAllowed: false,
    },
    {
      id: "data-2",
      name: "1.25GB Midnight",
      data: "1.25GB",
      minutes: null,
      sms: null,
      price: 55,
      validity: "Till midnight",
      category: "data" as const,
      multipleAllowed: false,
    },
    {
      id: "data-3",
      name: "1GB Hourly",
      data: "1GB",
      minutes: null,
      sms: null,
      price: 19,
      validity: "1 hour",
      category: "data" as const,
      multipleAllowed: false,
    },
    {
      id: "data-4",
      name: "1.5GB Express",
      data: "1.5GB",
      minutes: null,
      sms: null,
      price: 50,
      validity: "3 hours",
      category: "data" as const,
      multipleAllowed: false,
    },
    {
      id: "data-5",
      name: "350MB Weekly",
      data: "350MB",
      minutes: null,
      sms: null,
      price: 49,
      validity: "7 days",
      category: "data" as const,
      multipleAllowed: false,
    },
    {
      id: "data-6",
      name: "1GB Daily",
      data: "1GB",
      minutes: null,
      sms: null,
      price: 99,
      validity: "24 hours",
      category: "data" as const,
      multipleAllowed: false,
    },
  ],
  minutes: [
    {
      id: "min-1",
      name: "45 Minutes Express",
      data: null,
      minutes: "45 Minutes",
      sms: null,
      price: 22,
      validity: "3 hours",
      category: "minutes" as const,
      multipleAllowed: true,
    },
    {
      id: "min-2",
      name: "50 Minutes Midnight",
      data: null,
      minutes: "50 Minutes",
      sms: null,
      price: 51,
      validity: "Till midnight",
      category: "minutes" as const,
      multipleAllowed: true,
    },
  ],
  sms: [
    {
      id: "sms-1",
      name: "200 SMS Daily",
      data: null,
      minutes: null,
      sms: "200 SMS",
      price: 10,
      validity: "24 hours",
      category: "sms" as const,
      multipleAllowed: true,
    },
    {
      id: "sms-2",
      name: "100 SMS Weekly",
      data: null,
      minutes: null,
      sms: "100 SMS",
      price: 18,
      validity: "1 week",
      category: "sms" as const,
      multipleAllowed: true,
    },
    {
      id: "sms-3",
      name: "1000 SMS Weekly",
      data: null,
      minutes: null,
      sms: "1000 SMS",
      price: 30,
      validity: "1 week",
      category: "sms" as const,
      multipleAllowed: true,
    },
  ],
  data_multiple: [
    {
      id: "datam-1",
      name: "1GB Quick",
      data: "1GB",
      minutes: null,
      sms: null,
      price: 23,
      validity: "1 hour",
      category: "data_multiple" as const,
      multipleAllowed: true,
    },
    {
      id: "datam-2",
      name: "1.5GB Booster",
      data: "1.5GB",
      minutes: null,
      sms: null,
      price: 52,
      validity: "3 hours",
      category: "data_multiple" as const,
      multipleAllowed: true,
    },
    {
      id: "datam-3",
      name: "2GB Daily",
      data: "2GB",
      minutes: null,
      sms: null,
      price: 110,
      validity: "24 hours",
      category: "data_multiple" as const,
      multipleAllowed: true,
    },
  ],
};

router.get("/offers", async (_req, res): Promise<void> => {
  res.json(ListOffersResponse.parse(OFFERS));
});

export { OFFERS };
export default router;
